exports['Package Exported files 1'] = {
  "name": "vis-charts                              ",
  "files": [
    "        LICENSE-APACHE-2.0",
    "        LICENSE-MIT",
    "        README.md",
    "        declarations/index.d.ts",
    "        dist/img/network/acceptDeleteIcon.png",
    "        dist/img/network/addNodeIcon.png",
    "        dist/img/network/backIcon.png",
    "        dist/img/network/connectIcon.png",
    "        dist/img/network/cross.png",
    "        dist/img/network/cross2.png",
    "        dist/img/network/deleteIcon.png",
    "        dist/img/network/downArrow.png",
    "        dist/img/network/editIcon.png",
    "        dist/img/network/leftArrow.png",
    "        dist/img/network/minus.png",
    "        dist/img/network/plus.png",
    "        dist/img/network/rightArrow.png",
    "        dist/img/network/upArrow.png",
    "        dist/img/network/zoomExtends.png",
    "        dist/vis.css",
    "        dist/vis.css.map",
    "        dist/vis.js",
    "        dist/vis.js.map",
    "        dist/vis.min.css",
    "        dist/vis.min.css.map",
    "        dist/vis.min.js",
    "        dist/vis.min.js.map",
    "        package.json",
    "        styles/vis-charts.css",
    "        styles/vis-charts.css.map",
    "        styles/vis-charts.min.css",
    "        styles/vis-charts.min.css.map"
  ]
}
